# https://taskfile.dev

version: '3'

tasks:
  build:
    cmds:
    - go build -C . -o ./bin
  build-r:
    cmds:
    - go build -C . -o ./bin -ldflags "-s -w -H windowsgui"
  test:
    cmds:
    - go test -C ./gabagool -v
  install:
    cmds:
    - go install -ldflags "-s -w -H windowsgui" .
